version: '3.8'

services:
#  web:
#    build: ./apps
#    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
#    volumes:
#      - ./apps/:/usr/src/app/
#    ports:
#      - 8002:8000
#    depends_on:
#    - "db"

  db:
    image: postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=employment_exchange
